[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
amoy = "${POLYGON_AMOY_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
polygon = "${POLYGON_MAINNET_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"

[etherscan]
polygon-amoy = { key = "${POLYGONSCAN_API_KEY}", url = "https://polygon-amoy-bor-rpc.publicnode.com" }
base-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://base-sepolia.drpc.org" }
polygon = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# # Deploy to Polygon Amoy
# forge script script/Deploy.s.sol \
#   --rpc-url amoy \
#   --broadcast \
#   --verify \
#   --chain 80002

# # Or for Base Sepolia
# forge script script/Deploy.s.sol \
#   --rpc-url base_sepolia \
#   --broadcast \
#   --verify \
#   --chain 84532
